// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaE4XE8mT3MkH5MM47zc8DqXHTET-KI1w',
    appId: '1:950804897667:android:336cec4dff83493780e0b6',
    messagingSenderId: '950804897667',
    projectId: 'marathon-connect',
    databaseURL: 'https://marathon-connect-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'marathon-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXBm2gyNkEWVoyZ4VSAEI3Twj9BJpWYw0',
    appId: '1:950804897667:ios:f00be9b758b88a6480e0b6',
    messagingSenderId: '950804897667',
    projectId: 'marathon-connect',
    databaseURL: 'https://marathon-connect-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'marathon-connect.firebasestorage.app',
    androidClientId: '950804897667-9b5maiqh6qla3t0qk2j28jtfd2ieoh9g.apps.googleusercontent.com',
    iosClientId: '950804897667-92ufpn1kmot4pdplnmqat89ir7kbeg9i.apps.googleusercontent.com',
    iosBundleId: 'com.sportconnect.sportConnect',
  );

}