// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA39vZ2S0SyWWGKGR5Yo-FqzXpJvrWKTzY',
    appId: '1:950804897667:web:35fe380e9a6e27ef80e0b6',
    messagingSenderId: '950804897667',
    projectId: 'marathon-connect',
    authDomain: 'marathon-connect.firebaseapp.com',
    storageBucket: 'marathon-connect.firebasestorage.app',
    measurementId: 'G-29WZE5WH4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaE4XE8mT3MkH5MM47zc8DqXHTET-KI1w',
    appId: '1:950804897667:android:336cec4dff83493780e0b6',
    messagingSenderId: '950804897667',
    projectId: 'marathon-connect',
    storageBucket: 'marathon-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXBm2gyNkEWVoyZ4VSAEI3Twj9BJpWYw0',
    appId: '1:950804897667:ios:f00be9b758b88a6480e0b6',
    messagingSenderId: '950804897667',
    projectId: 'marathon-connect',
    storageBucket: 'marathon-connect.firebasestorage.app',
    iosBundleId: 'com.sportconnect.sportConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXBm2gyNkEWVoyZ4VSAEI3Twj9BJpWYw0',
    appId: '1:950804897667:ios:f00be9b758b88a6480e0b6',
    messagingSenderId: '950804897667',
    projectId: 'marathon-connect',
    storageBucket: 'marathon-connect.firebasestorage.app',
    iosBundleId: 'com.sportconnect.sportConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA39vZ2S0SyWWGKGR5Yo-FqzXpJvrWKTzY',
    appId: '1:950804897667:web:14230de23dab235980e0b6',
    messagingSenderId: '950804897667',
    projectId: 'marathon-connect',
    authDomain: 'marathon-connect.firebaseapp.com',
    storageBucket: 'marathon-connect.firebasestorage.app',
    measurementId: 'G-E0ZBLTCHH3',
  );

}