// Mocks generated by Mockito 5.4.6 from annotations
// in sport_connect/test/core/interfaces/mock_repositories.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:io' as _i9;

import 'package:cloud_firestore/cloud_firestore.dart' as _i4;
import 'package:firebase_auth/firebase_auth.dart' as _i3;
import 'package:firebase_messaging/firebase_messaging.dart' as _i6;
import 'package:firebase_storage/firebase_storage.dart' as _i5;
import 'package:geolocator/geolocator.dart' as _i19;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i10;
import 'package:sport_connect/core/interfaces/repositories/i_auth_repository.dart'
    as _i7;
import 'package:sport_connect/core/interfaces/repositories/i_chat_repository.dart'
    as _i15;
import 'package:sport_connect/core/interfaces/repositories/i_ride_repository.dart'
    as _i12;
import 'package:sport_connect/core/interfaces/repositories/i_user_repository.dart'
    as _i11;
import 'package:sport_connect/core/interfaces/services/i_firebase_service.dart'
    as _i17;
import 'package:sport_connect/core/interfaces/services/i_location_service.dart'
    as _i18;
import 'package:sport_connect/features/auth/models/models.dart' as _i2;
import 'package:sport_connect/features/messaging/models/message_model.dart'
    as _i16;
import 'package:sport_connect/features/rides/models/ride/ride_model.dart'
    as _i13;
import 'package:sport_connect/features/rides/models/ride_request_model.dart'
    as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSocialSignInResult_0 extends _i1.SmartFake
    implements _i2.SocialSignInResult {
  _FakeSocialSignInResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_1 extends _i1.SmartFake
    implements _i3.UserCredential {
  _FakeUserCredential_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseAuth_2 extends _i1.SmartFake implements _i3.FirebaseAuth {
  _FakeFirebaseAuth_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseFirestore_3 extends _i1.SmartFake
    implements _i4.FirebaseFirestore {
  _FakeFirebaseFirestore_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseStorage_4 extends _i1.SmartFake
    implements _i5.FirebaseStorage {
  _FakeFirebaseStorage_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseMessaging_5 extends _i1.SmartFake
    implements _i6.FirebaseMessaging {
  _FakeFirebaseMessaging_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCollectionReference_6<T extends Object?> extends _i1.SmartFake
    implements _i4.CollectionReference<T> {
  _FakeCollectionReference_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDocumentReference_7<T extends Object?> extends _i1.SmartFake
    implements _i4.DocumentReference<T> {
  _FakeDocumentReference_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [IAuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAuthRepository extends _i1.Mock implements _i7.IAuthRepository {
  MockIAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<_i3.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i8.Stream<_i3.User?>.empty(),
          )
          as _i8.Stream<_i3.User?>);

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  _i8.Future<_i2.UserModel?> signInWithEmail(
    String? email,
    String? password,
    bool? rememberMe,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [email, password, rememberMe]),
            returnValue: _i8.Future<_i2.UserModel?>.value(),
          )
          as _i8.Future<_i2.UserModel?>);

  @override
  _i8.Future<_i2.UserModel?> registerWithEmail({
    required String? email,
    required String? password,
    required String? displayName,
    required _i2.UserRole? role,
    String? phone,
    String? bio,
    List<String>? interests = const [],
    _i9.File? profileImage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#registerWithEmail, [], {
              #email: email,
              #password: password,
              #displayName: displayName,
              #role: role,
              #phone: phone,
              #bio: bio,
              #interests: interests,
              #profileImage: profileImage,
            }),
            returnValue: _i8.Future<_i2.UserModel?>.value(),
          )
          as _i8.Future<_i2.UserModel?>);

  @override
  _i8.Future<_i2.SocialSignInResult> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i8.Future<_i2.SocialSignInResult>.value(
              _FakeSocialSignInResult_0(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i8.Future<_i2.SocialSignInResult>);

  @override
  _i8.Future<_i2.SocialSignInResult> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i8.Future<_i2.SocialSignInResult>.value(
              _FakeSocialSignInResult_0(
                this,
                Invocation.method(#signInWithApple, []),
              ),
            ),
          )
          as _i8.Future<_i2.SocialSignInResult>);

  @override
  _i8.Future<_i2.UserModel?> getUserData(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, [uid]),
            returnValue: _i8.Future<_i2.UserModel?>.value(),
          )
          as _i8.Future<_i2.UserModel?>);

  @override
  _i8.Stream<_i2.UserModel?> getUserDataStream(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserDataStream, [uid]),
            returnValue: _i8.Stream<_i2.UserModel?>.empty(),
          )
          as _i8.Stream<_i2.UserModel?>);

  @override
  _i8.Future<void> updateUserData(_i2.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserData, [user]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> reauthenticateWithPassword(String? password) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithPassword, [password]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> reauthenticateWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithGoogle, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> isEmailVerified() =>
      (super.noSuchMethod(
            Invocation.method(#isEmailVerified, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> reloadUser() =>
      (super.noSuchMethod(
            Invocation.method(#reloadUser, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> verifyPhoneNumber({
    required String? phoneNumber,
    required void Function(String, int?)? onCodeSent,
    required void Function(String)? onAutoRetrievalTimeout,
    required void Function(_i3.FirebaseAuthException)? onVerificationFailed,
    required void Function(_i3.PhoneAuthCredential)? onVerificationCompleted,
    int? forceResendingToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPhoneNumber, [], {
              #phoneNumber: phoneNumber,
              #onCodeSent: onCodeSent,
              #onAutoRetrievalTimeout: onAutoRetrievalTimeout,
              #onVerificationFailed: onVerificationFailed,
              #onVerificationCompleted: onVerificationCompleted,
              #forceResendingToken: forceResendingToken,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i3.UserCredential> signInWithPhoneCredential({
    required String? verificationId,
    required String? smsCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPhoneCredential, [], {
              #verificationId: verificationId,
              #smsCode: smsCode,
            }),
            returnValue: _i8.Future<_i3.UserCredential>.value(
              _FakeUserCredential_1(
                this,
                Invocation.method(#signInWithPhoneCredential, [], {
                  #verificationId: verificationId,
                  #smsCode: smsCode,
                }),
              ),
            ),
          )
          as _i8.Future<_i3.UserCredential>);

  @override
  _i8.Future<_i3.UserCredential> signInWithPhoneAutoCredential(
    _i3.PhoneAuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithPhoneAutoCredential, [credential]),
            returnValue: _i8.Future<_i3.UserCredential>.value(
              _FakeUserCredential_1(
                this,
                Invocation.method(#signInWithPhoneAutoCredential, [credential]),
              ),
            ),
          )
          as _i8.Future<_i3.UserCredential>);

  @override
  _i8.Future<String?> uploadProfileImage(_i9.File? image, String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProfileImage, [image, uid]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> updateUserRole(String? uid, _i2.UserRole? role) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserRole, [uid, role]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearNeedsRoleSelection(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#clearNeedsRoleSelection, [uid]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i2.UserModel> createUserDocument(_i2.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUserDocument, [user]),
            returnValue: _i8.Future<_i2.UserModel>.value(
              _i10.dummyValue<_i2.UserModel>(
                this,
                Invocation.method(#createUserDocument, [user]),
              ),
            ),
          )
          as _i8.Future<_i2.UserModel>);

  @override
  _i8.Future<void> updateUserStats({
    required String? userId,
    int? xpIncrement,
    int? ridesOfferedIncrement,
    int? ridesCompletedIncrement,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserStats, [], {
              #userId: userId,
              #xpIncrement: xpIncrement,
              #ridesOfferedIncrement: ridesOfferedIncrement,
              #ridesCompletedIncrement: ridesCompletedIncrement,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [IUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIUserRepository extends _i1.Mock implements _i11.IUserRepository {
  MockIUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.UserModel?> getUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i8.Future<_i2.UserModel?>.value(),
          )
          as _i8.Future<_i2.UserModel?>);

  @override
  _i8.Future<List<_i2.UserModel>> searchUsers({
    String? query,
    _i2.UserRole? role,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [], {
              #query: query,
              #role: role,
              #limit: limit,
            }),
            returnValue: _i8.Future<List<_i2.UserModel>>.value(
              <_i2.UserModel>[],
            ),
          )
          as _i8.Future<List<_i2.UserModel>>);

  @override
  _i8.Future<void> updateUser(_i2.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateUserField(
    String? userId,
    String? field,
    dynamic value,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserField, [userId, field, value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateOnlineStatus(String? userId, bool? isOnline) =>
      (super.noSuchMethod(
            Invocation.method(#updateOnlineStatus, [userId, isOnline]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<bool> getUserOnlineStatus(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserOnlineStatus, [userId]),
            returnValue: _i8.Stream<bool>.empty(),
          )
          as _i8.Stream<bool>);
}

/// A class which mocks [IRideRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIRideRepository extends _i1.Mock implements _i12.IRideRepository {
  MockIRideRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String> createRide(_i13.RideModel? ride) =>
      (super.noSuchMethod(
            Invocation.method(#createRide, [ride]),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#createRide, [ride]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<_i13.RideModel?> getRideById(String? rideId) =>
      (super.noSuchMethod(
            Invocation.method(#getRideById, [rideId]),
            returnValue: _i8.Future<_i13.RideModel?>.value(),
          )
          as _i8.Future<_i13.RideModel?>);

  @override
  _i8.Future<void> updateRide(_i13.RideModel? ride) =>
      (super.noSuchMethod(
            Invocation.method(#updateRide, [ride]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteRide(String? rideId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRide, [rideId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i13.RideModel>> searchRides({
    required double? originLat,
    required double? originLng,
    required double? destLat,
    required double? destLng,
    DateTime? date,
    int? minSeats,
    double? maxPrice,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchRides, [], {
              #originLat: originLat,
              #originLng: originLng,
              #destLat: destLat,
              #destLng: destLng,
              #date: date,
              #minSeats: minSeats,
              #maxPrice: maxPrice,
            }),
            returnValue: _i8.Future<List<_i13.RideModel>>.value(
              <_i13.RideModel>[],
            ),
          )
          as _i8.Future<List<_i13.RideModel>>);

  @override
  _i8.Stream<List<_i13.RideModel>> getActiveRides(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getActiveRides, [userId]),
            returnValue: _i8.Stream<List<_i13.RideModel>>.empty(),
          )
          as _i8.Stream<List<_i13.RideModel>>);

  @override
  _i8.Stream<List<_i13.RideModel>> getRideHistory(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getRideHistory, [userId]),
            returnValue: _i8.Stream<List<_i13.RideModel>>.empty(),
          )
          as _i8.Stream<List<_i13.RideModel>>);

  @override
  _i8.Future<String> createRideRequest(_i14.RideRequestModel? request) =>
      (super.noSuchMethod(
            Invocation.method(#createRideRequest, [request]),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#createRideRequest, [request]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<_i14.RideRequestModel?> getRideRequest(String? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#getRideRequest, [requestId]),
            returnValue: _i8.Future<_i14.RideRequestModel?>.value(),
          )
          as _i8.Future<_i14.RideRequestModel?>);

  @override
  _i8.Future<void> updateRideRequest(_i14.RideRequestModel? request) =>
      (super.noSuchMethod(
            Invocation.method(#updateRideRequest, [request]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> acceptRideRequest(String? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#acceptRideRequest, [requestId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> rejectRideRequest(String? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#rejectRideRequest, [requestId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<List<_i14.RideRequestModel>> getRideRequests(String? rideId) =>
      (super.noSuchMethod(
            Invocation.method(#getRideRequests, [rideId]),
            returnValue: _i8.Stream<List<_i14.RideRequestModel>>.empty(),
          )
          as _i8.Stream<List<_i14.RideRequestModel>>);

  @override
  _i8.Future<void> startRide(String? rideId) =>
      (super.noSuchMethod(
            Invocation.method(#startRide, [rideId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> completeRide(String? rideId) =>
      (super.noSuchMethod(
            Invocation.method(#completeRide, [rideId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> cancelRide(String? rideId, String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#cancelRide, [rideId, reason]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [IChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIChatRepository extends _i1.Mock implements _i15.IChatRepository {
  MockIChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<String> createChat(_i16.ChatModel? chat) =>
      (super.noSuchMethod(
            Invocation.method(#createChat, [chat]),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#createChat, [chat]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<_i16.ChatModel?> getChatById(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getChatById, [chatId]),
            returnValue: _i8.Future<_i16.ChatModel?>.value(),
          )
          as _i8.Future<_i16.ChatModel?>);

  @override
  _i8.Future<_i16.ChatModel?> getOrCreateDirectChat(
    String? userId1,
    String? userId2,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateDirectChat, [userId1, userId2]),
            returnValue: _i8.Future<_i16.ChatModel?>.value(),
          )
          as _i8.Future<_i16.ChatModel?>);

  @override
  _i8.Stream<List<_i16.ChatModel>> getUserChats(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserChats, [userId]),
            returnValue: _i8.Stream<List<_i16.ChatModel>>.empty(),
          )
          as _i8.Stream<List<_i16.ChatModel>>);

  @override
  _i8.Future<String> sendMessage(_i16.MessageModel? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [message]),
            returnValue: _i8.Future<String>.value(
              _i10.dummyValue<String>(
                this,
                Invocation.method(#sendMessage, [message]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> deleteMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> markAsRead(String? chatId, String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#markAsRead, [chatId, userId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<List<_i16.MessageModel>> getChatMessages(
    String? chatId, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getChatMessages, [chatId], {#limit: limit}),
            returnValue: _i8.Stream<List<_i16.MessageModel>>.empty(),
          )
          as _i8.Stream<List<_i16.MessageModel>>);

  @override
  _i8.Future<void> setTypingStatus(
    String? chatId,
    String? userId,
    bool? isTyping,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setTypingStatus, [chatId, userId, isTyping]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<Map<String, bool>> getTypingStatus(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getTypingStatus, [chatId]),
            returnValue: _i8.Stream<Map<String, bool>>.empty(),
          )
          as _i8.Stream<Map<String, bool>>);
}

/// A class which mocks [IFirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockIFirebaseService extends _i1.Mock implements _i17.IFirebaseService {
  MockIFirebaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FirebaseAuth get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeFirebaseAuth_2(this, Invocation.getter(#auth)),
          )
          as _i3.FirebaseAuth);

  @override
  _i4.FirebaseFirestore get firestore =>
      (super.noSuchMethod(
            Invocation.getter(#firestore),
            returnValue: _FakeFirebaseFirestore_3(
              this,
              Invocation.getter(#firestore),
            ),
          )
          as _i4.FirebaseFirestore);

  @override
  _i5.FirebaseStorage get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeFirebaseStorage_4(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i5.FirebaseStorage);

  @override
  _i6.FirebaseMessaging get messaging =>
      (super.noSuchMethod(
            Invocation.getter(#messaging),
            returnValue: _FakeFirebaseMessaging_5(
              this,
              Invocation.getter(#messaging),
            ),
          )
          as _i6.FirebaseMessaging);

  @override
  _i8.Stream<_i3.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i8.Stream<_i3.User?>.empty(),
          )
          as _i8.Stream<_i3.User?>);

  @override
  _i4.CollectionReference<Map<String, dynamic>> get usersCollection =>
      (super.noSuchMethod(
            Invocation.getter(#usersCollection),
            returnValue: _FakeCollectionReference_6<Map<String, dynamic>>(
              this,
              Invocation.getter(#usersCollection),
            ),
          )
          as _i4.CollectionReference<Map<String, dynamic>>);

  @override
  bool get useEmulators =>
      (super.noSuchMethod(Invocation.getter(#useEmulators), returnValue: false)
          as bool);

  @override
  _i8.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i4.DocumentReference<Map<String, dynamic>> getUserDoc(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getUserDoc, [uid]),
            returnValue: _FakeDocumentReference_7<Map<String, dynamic>>(
              this,
              Invocation.method(#getUserDoc, [uid]),
            ),
          )
          as _i4.DocumentReference<Map<String, dynamic>>);

  @override
  _i8.Future<void> connectToEmulators() =>
      (super.noSuchMethod(
            Invocation.method(#connectToEmulators, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [ILocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocationService extends _i1.Mock implements _i18.ILocationService {
  MockILocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<bool> checkPermission() =>
      (super.noSuchMethod(
            Invocation.method(#checkPermission, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<bool> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i19.Position?> getCurrentLocation() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLocation, []),
            returnValue: _i8.Future<_i19.Position?>.value(),
          )
          as _i8.Future<_i19.Position?>);

  @override
  _i8.Stream<_i19.Position> getLocationStream() =>
      (super.noSuchMethod(
            Invocation.method(#getLocationStream, []),
            returnValue: _i8.Stream<_i19.Position>.empty(),
          )
          as _i8.Stream<_i19.Position>);

  @override
  double calculateDistance(
    double? lat1,
    double? lon1,
    double? lat2,
    double? lon2,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#calculateDistance, [lat1, lon1, lat2, lon2]),
            returnValue: 0.0,
          )
          as double);

  @override
  _i8.Future<String?> getAddressFromCoordinates(double? lat, double? lon) =>
      (super.noSuchMethod(
            Invocation.method(#getAddressFromCoordinates, [lat, lon]),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<_i19.Position?> getCoordinatesFromAddress(String? address) =>
      (super.noSuchMethod(
            Invocation.method(#getCoordinatesFromAddress, [address]),
            returnValue: _i8.Future<_i19.Position?>.value(),
          )
          as _i8.Future<_i19.Position?>);
}
